<?php 
$class = (isset($item['class'])) ? $item['class'] : '';

$data = (isset($item['event'])) ? ' data-event="'.$item['event'].'"' : '';
?>

<input type="text" <?php echo $data;?>  class="<?php echo $class ;?> " name="<?php echo $ident; ?>" value ='<?php echo $currentValue[$ident]; ?>' >
for plural: <input type="text" <?php echo $data;?>  class="<?php echo $class ;?> " name="<?php echo $ident.'Plural'; ?>" value ='<?php echo $currentValue[$ident.'Plural']; ?>' >