<?php
$multipleSymbol = '';


if (isset($item['attr'])) {
    $multipleSymbol = '[]';
}

if (!isset($currentValue)) {
    $currentValue = array();
}

if (!is_array($currentValue)) {
    $currentValue = array($currentValue);
}

?>
<select name="<?php echo $ident.$multipleSymbol; ?>">
    <?php
    foreach ($item['values'] as $value => $key) {
        $selected = ($currentValue == $value || in_array($value, $currentValue) == TRUE) ? ' selected="selected"' : '';
        ?>
        <option value="<?php echo $value; ?>"<?php echo $selected; ?>><?php echo $key; ?></option>
        <?php
    }
    ?>
