<?php 
$right = '';
$left = '';

if ($settings['menuCartPosition'] == 0) {
    $right = $menu;  
}
else {
    $left = $menu;
}
?>
<?php echo $left; ?>
<li style="list-style: none;">
     <?php if (array_key_exists('customizeCartInMenu', $settings) && !empty($settings['customizeCartInMenu'])) { 
     }
     ?>

    <?php echo $this->fetchCart('festi-cart-menu'); ?>
    <?php if (array_key_exists('customizeCartInMenu', $settings) && !empty($settings['customizeCartInMenu'])) {

     }
     ?>

</li>
<?php echo $right; ?>